Repository WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Original-Digitals, pull requests merged in 2024-09, with the labels that each got.

#2 Initialize databases
  server/app/config.js
  server/app/controllers/movieActions.js
  server/app/router.js
  server/database/models/MovieRepository.js
  server/database/schema.sql
  server/database/tables.js
  server/package.json
Labels: REVIEWED

#3 🗃️ adding add youtubes links in movie table
  server/database/schema.sql
Labels: REVIEW REQUESTED

#5 :building_construction: create path for select movie by id
  server/app/controllers/movieActions.js
  server/app/router.js
  server/database/models/MovieRepository.js
Labels: REVIEWED

#4 U02 video list request
  client/package.json
  client/src/App.jsx
  client/src/components/MovieCard.jsx
  client/src/components/MoviesList.jsx
  client/src/main.jsx
  client/src/services/request.js
Labels: CORRECTIONS DONE, REVIEWED

#6 U02 video list update video
  client/package.json
  client/src/App.jsx
  client/src/components/MovieCard.jsx
  client/src/main.jsx
  client/src/pages/MoviesList.jsx
  client/src/styles/Moviecard.css
  client/src/styles/Movielist.css
Labels: REVIEWED

#7 U01 user creation form
  client/src/App.css
  client/src/App.jsx
  client/src/components/NavBar.jsx
  client/src/components/UserForm.jsx
  client/src/main.jsx
  client/src/pages/SignUp.jsx
  client/src/pages/User.jsx
  client/src/services/myAxios.js
  client/src/services/request.js
  client/src/services/userService.js
  client/src/styles/Navbar.css
  client/src/styles/Signup.css
  client/src/styles/Userform.css
  client/src/styles/fonts/Nunito-VariableFont_wght.ttf
  server/app/controllers/userActions.js
  server/app/router.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#8 U01 landing
  client/src/App.css
  client/src/App.jsx
  client/src/assets/images/YouFilm-01.png
  client/src/assets/images/YouFilm-02.png
  client/src/assets/images/YouFilm-03.png
  client/src/assets/images/films-banner.png
  client/src/main.jsx
  client/src/pages/Home.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/SignUp.jsx
  client/src/styles/Landing.css
  client/src/styles/Signup.css
Labels: REVIEWED

#12 U01 user auth backend
  client/src/components/UserForm.jsx
  client/src/services/userService.js
  server/app/controllers/authActions.js
  server/app/router.js
  server/app/services/auth.js
  server/app/services/middleware.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/package.json
Labels: REVIEWED

#13 U31 panel admin
  client/src/App.css
  client/src/components/AdminNavBar.jsx
  client/src/components/ContentManagement.jsx
  client/src/components/UserForm.jsx
  client/src/components/UserManagement.jsx
  client/src/main.jsx
  client/src/pages/AdminPanel.jsx
  client/src/services/adminService.js
  client/src/styles/Adminpanel.css
  package-lock.json
  server/app/controllers/movieActions.js
  server/app/router.js
  server/database/models/MovieRepository.js
Labels: REVIEW REQUESTED, REVIEWED

#18 U01 user account
  client/src/App.css
  client/src/App.jsx
  client/src/components/AccountManagement.jsx
  client/src/components/MovieDetails.jsx
  client/src/components/NavBar.jsx
  client/src/components/PasswordManagement.jsx
  client/src/components/PreferenceManagement.jsx
  client/src/components/UserNavBar.jsx
  client/src/contexts/AuthContext.jsx
  client/src/main.jsx
  client/src/pages/User.jsx
  client/src/services/request.js
  client/src/services/userService.js
  client/src/styles/Moviedetails.css
  client/src/styles/Userpanel.css
  server/app/controllers/userActions.js
  server/app/router.js
  server/app/services/auth.js
  server/database/models/UserRepository.js
Labels: REVIEWED

#17 U03 02 homepage
  client/src/main.jsx
  client/src/pages/Home.jsx
  client/src/services/request.js
  server/app/controllers/categoryActions.js
  server/app/controllers/movieActions.js
  server/app/router.js
  server/database/models/MovieRepository.js
  server/database/models/categoryRespository.js
  server/database/schema.sql
  server/database/tables.js
Labels: CONFLICTS RESOLVED, REVIEWED

#19 U08 1 search fix
  client/src/components/NavBar.jsx
Labels: REVIEWED

#22 ✨ creating a function edit for movies.
  server/app/controllers/movieActions.js
  server/app/router.js
  server/database/models/MovieRepository.js
  server/database/models/UserRepository.js
Labels: REVIEWED

#20 U04 1 account logout
  client/src/App.jsx
  client/src/components/LogoutButton.jsx
  client/src/components/NavBar.jsx
  client/src/components/UserNavBar.jsx
  client/src/contexts/AuthContext.jsx
  client/src/main.jsx
  client/src/pages/Home.jsx
  client/src/pages/Login.jsx
  client/src/pages/SignIn.jsx
  client/src/pages/User.jsx
  client/src/services/request.js
  client/src/services/userService.js
  client/src/styles/Navbar.css
  client/src/styles/Userpanel.css
  server/app/router.js
  server/app/services/auth.js
Labels: REVIEWED

#24 U03 2 carrousel
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/Carousel.jsx
  client/src/components/MovieCard.jsx
  client/src/pages/Home.jsx
  client/src/styles/Carousel.css
  client/src/styles/Moviecard.css
Labels: CORRECTIONS DONE, REVIEWED

#25 :card_file_box: update base data with new links, update moviecards to…
  client/src/main.jsx
  server/database/schema.sql
Labels: REVIEWED

#23 U04 2 account delete
  client/src/App.jsx
  client/src/components/CustomModal.jsx
  client/src/components/PreferenceManagement.jsx
  client/src/styles/Custommodal.css
  client/src/styles/Userpanel.css
  server/app/controllers/userActions.js
  server/app/router.js
  server/database/models/UserRepository.js
Labels: REVIEWED

#27 U32 edit
  client/src/components/AdminNavBar.jsx
  client/src/components/ContentManagement.jsx
  client/src/components/MovieEdit.jsx
  client/src/components/MovieFormEdit.jsx
  client/src/components/MovieSelection.jsx
  client/src/components/MovieUpdateDetails.jsx
  client/src/main.jsx
  client/src/pages/AdminPanel.jsx
  client/src/services/adminService.js
  client/src/services/utils.js
  client/src/styles/Movieedit.css
Labels: REVIEW REQUESTED

#28 DB data fix
  server/database/schema.sql
Labels: REVIEWED

#29 🔀 merge u02_free_movies_page into dev
  server/app/controllers/movieActions.js
  server/app/router.js
  server/database/models/MovieRepository.js
  server/database/schema.sql
Labels: REVIEWED

#32 🔀 Merge free movies functionality: backend and frontend integration
  client/src/main.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/MoviesFreeList.jsx
  client/src/services/request.js
Labels: REVIEWED

#33 U07 watchlist backend
  server/app/controllers/userActions.js
  server/app/controllers/watchlistActions.js
  server/app/router.js
  server/database/models/WatchlistRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#34 🔀Update movies: Set 10 existing movies as free
  server/database/schema.sql
Labels: REVIEWED

#31 U33 admin delete
  client/src/components/MovieEdit.jsx
  client/src/components/MovieSelection.jsx
  client/src/components/NavBar.jsx
  server/app/controllers/movieActions.js
  server/app/router.js
  server/database/models/MovieCategoryRepository.js
  server/database/models/MovieRepository.js
  server/database/tables.js
Labels: REVIEWED

#35 U07 watchlist frontend
  client/src/assets/images/watchlist.svg
  client/src/assets/images/watchlisted.svg
  client/src/components/MovieCard.jsx
  client/src/components/MovieDetails.jsx
  client/src/components/NavBar.jsx
  client/src/components/WatchListButton.jsx
  client/src/main.jsx
  client/src/pages/Watchlist.jsx
  client/src/services/request.js
  client/src/styles/Moviedetails.css
  server/app/controllers/watchlistActions.js
  server/app/router.js
Labels: REVIEWED

#36 :sparkles: add a root for adminPanel when the role admin is defined i…
  client/src/components/NavBar.jsx
  client/src/contexts/AuthContext.jsx
  client/src/pages/Login.jsx
Labels: REVIEWED

#37 Backend routing security
  client/src/services/request.js
  server/app/router.js
Labels: REVIEWED

#38 Fix u01 user
  client/src/components/NavBar.jsx
  client/src/components/PreferenceManagement.jsx
  client/src/main.jsx
  client/src/services/request.js
  client/src/services/userService.js
  server/app/controllers/userActions.js
  server/app/router.js
Labels: REVIEWED

#39 🔀CSS : Add desktop version of landing page layout
  client/src/assets/images/YouFlim-01.png
  client/src/assets/images/desktop-mobile-tab.png
  client/src/assets/images/exit-logo.png
  client/src/components/AccountManagement.jsx
  client/src/components/MovieEdit.jsx
  client/src/components/MovieFormEdit.jsx
  client/src/components/MovieSelection.jsx
  client/src/components/MovieUpdateDetails.jsx
  client/src/components/PasswordManagement.jsx
  client/src/main.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/Login.jsx
  client/src/pages/MoviesFreeList.jsx
  client/src/services/request.js
  client/src/services/utils.js
  client/src/styles/Landing.css
Labels: REVIEWED

#41 Login & Sign Up desktop versions
  client/src/components/UserForm.jsx
  client/src/pages/Login.jsx
  client/src/pages/SignUp.jsx
  client/src/styles/Signin.css
  client/src/styles/Signup.css
  client/src/styles/Userform.css
Labels: REVIEWED

#44 :lipstick: add desktop and styling to watchlist, as well as carrousel
  client/src/pages/Watchlist.jsx
Labels: REVIEWED

#45 :lipstick: favicon change, moviedetails improvement with new buttons …
  client/index.html
  client/src/assets/favicon.ico
  client/src/components/MovieDetails.jsx
  client/src/components/WatchListButton.jsx
  client/src/styles/Moviedetails.css
Labels: REVIEWED

#47 U08 2 search genre
  client/src/components/NavBar.jsx
  client/src/components/Search.jsx
  client/src/pages/MoviesList.jsx
  client/src/styles/Navbar.css
Labels: REVIEWED

#48 🚧 add a condition to remove navbar in adminpannel
  client/src/App.jsx
  client/src/components/MovieFormEdit.jsx
  client/src/components/NavBar.jsx
  client/src/styles/Adminpanel.css
Labels: REVIEWED
